### ISSUE TITLE
implement anomaly detection in time series of graphs

### ISSUE THREAD

**Issue by bdpedigo** [graspologic-org/graspologic#390]
paper forthcoming

**Comment by jovo** [comment]
@bdpedigo this became important, as per cep's request, because JL@MSR wants it in graspy now. 
Guodong has an R package, so it should be a simple matter of porting to `python`, unclear who is the right person for this?
Maybe @j1c ?

**Comment by bdpedigo** [comment]
@jovo could we get more context? you have the R code/paper (I think I saw a pdf a long time ago but haven't seen anything recently)?

**Comment by jovo** [comment]
Ask Guodong

On Fri, Aug 14, 2020 at 11:41 AM Benjamin Pedigo <notifications@github.com>
wrote:

>
>
>
>
>
>
>
>
>
>
>
> *      External Email - Use Caution      *
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
> @jovo
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjovo&data=02%7C01%7Cjovo%40jhu.edu%7C432feef48f8c483d099d08d8406883ff%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637330165530528865&sdata=rmK1Q6%2By%2BDvI%2B05jE1RZWVz6EY%2FZNi7J%2FNosnCO6y70%3D&reserved=0>
> could we get more context? you have the R
>
> code/paper (I think I saw a pdf a long time ago but haven't seen anything
> recently)?
>
>
> —
>
>
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly,
>
> view it on GitHub
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fneurodata%2Fgraspy%2Fissues%2F390%23issuecomment-674135512&data=02%7C01%7Cjovo%40jhu.edu%7C432feef48f8c483d099d08d8406883ff%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637330165530538859&sdata=PTzI3k58KWUfb0NGcJtyjR1dL7iWutNsgpab%2FXdszKA%3D&reserved=0>,
> or
>
> unsubscribe
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAAKG4U6CSTNCKQVFK4RUJ3SAVLKTANCNFSM4PW7GMUQ&data=02%7C01%7Cjovo%40jhu.edu%7C432feef48f8c483d099d08d8406883ff%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637330165530538859&sdata=3N3qUlXFLoyhIeGfyRBQ%2BZvR7QaqKxHa2mdxoFJCs7c%3D&reserved=0>
> .
>
>
>
>
>
>
>
>
> --
Typed with thumbs

**Comment by j1c** [comment]
@bdpedigo Thoughts on api? There are few wrinkles in this.

1. There is no out of sample prediction. You train and predict on the input dataset, so standard `fit` and `fit_predict` doesn't make sense. It could be a class with just `fit_predict`, but then it could just be a function.
2. There is graph-wise and vertex-wise anomaly detection. But the embedding process is the same for both, so you can do both graph-wise and vertex-wise anomaly detection with one set of embeddings.  

So things to decide is:
- Should graph-wise and vertex-wise be in same class/function or separate. I think it make sense to include both in same class/function since embedding is the more computationally intensive part
- Should it be a function or class. With function, it requires 5+ things to be returned, but it also doesn't conform to classic sklearn style class. We could do something like mgc does and return `(graph_anomaly_indices, graph_anomaly_dict, vertex_anomaly_indices, vertex_anomaly_dict)` or something along those lines. No opinions on this one.

**Comment by bdpedigo** [comment]
- From your description, I agree that graph-wise and vertex-wise make sense in the same class/function
- class/function is a bit harder. ya, it sounds like neither are super convenient. I guess this is why scipy has stuff like [OptimizeResult](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.OptimizeResult.html) which is basically just a dict. Though I actually don't know if there are any advantages to using that over just a dict, normally I'd say no to a class just to store data right? I feel like based on all of this I'm leaning towards function w/ dict output but we could also ask Dwayne.

**Comment by loftusa** [comment]
@bdpedigo do we still want this?

**Comment by loftusa** [comment]
[guodong's paper](https://arxiv.org/pdf/2008.10055)
[book section](http://docs.neurodata.io/graph-stats-book/applications/ch10/anomaly-detection.html)

one issue I ran into while implementing this / playing around with it in python is that it's super not robust to embedding dimension. As in, I looked at the distribution of true test statistics under the null and bootstrapped test statistics under the null, and if the embedding dimension is different, they look completely different from each other and the test is broken. See below.


<img width="452" alt="Screen Shot 2021-11-15 at 5 02 59 PM" src="https://user-images.githubusercontent.com/12386450/142460782-0dca3b6f-d2e7-40ff-825a-50ef44e01da7.png">

![n100_m2_rdpg_dhat_be_1](https://user-images.githubusercontent.com/12386450/142460908-bb759f23-bb6c-4acd-ad89-c936c2264c5d.png)

This issue is somewhat alleviated in practice if you embed every adjacency matrix you have at once and then just take pairs (maybe since the variance is lower?) but you'll still get a pretty big bias.

Was thinking of hopping on zoom with Guodong at some point to talk about this

**Comment by bdpedigo** [comment]
> @bdpedigo @j1c do we still want this? I have code in a jupyter notebook I wrote for the book I'm about to clean up

my first question would be "what is someone going to use it for" - generally speaking I only think it is worth maintaining code that is being used by us/MSR/someone else. To me, if it is _just_ for the book, that doesn't feel like a compelling enough case IMO
